#!/bin/bash
set -euo pipefail

project_dir="$(cd "$(dirname "$0")" && pwd)"
override_file="$project_dir/compose.override.yaml"
marker="# Generated by setup-storage.sh -- safe to regenerate"
desktop_uid=1000
if [[ -r "$project_dir/.env" ]]; then
  configured_uid="$(awk -F= '$1 == "DESKTOP_UID" {print $2; exit}' "$project_dir/.env")"
  if [[ "$configured_uid" =~ ^[0-9]+$ ]]; then
    desktop_uid="$configured_uid"
  fi
fi
host_user="$(getent passwd "$desktop_uid" | cut -d: -f1 || true)"
if [[ -n "$host_user" ]]; then
  host_gid="$(id -g "$host_user")"
else
  host_gid="$desktop_uid"
fi

mapfile -t volume_roots < <(
  findmnt -rn -o TARGET | awk '/^\/vol[0-9]+$/ {print}' | sort -V
)

if ((${#volume_roots[@]} == 0)); then
  echo "没有检测到 /vol1、/vol2 等 fnOS 存储卷。" >&2
  exit 2
fi

volume_paths=()
for volume_root in "${volume_roots[@]}"; do
  user_path="$volume_root/$desktop_uid"
  if [[ -d "$user_path" ]]; then
    volume_paths+=("$user_path")
  else
    echo "跳过 $volume_root：没有用户目录 $user_path"
  fi
done
if ((${#volume_paths[@]} == 0)); then
  echo "没有找到可映射的 /volN/$desktop_uid 用户目录。" >&2
  exit 4
fi

if [[ -e "$override_file" ]] && ! grep -Fxq "$marker" "$override_file"; then
  echo "$override_file 已存在且不是本脚本生成，已停止以免覆盖。" >&2
  exit 3
fi

tmp_file="$(mktemp "$project_dir/.compose-storage.XXXXXX")"
trap 'rm -f "$tmp_file"' EXIT
{
  echo "$marker"
  echo "services:"
  echo "  ubuntu26-gnome-hdmi:"
  echo "    environment:"
  printf '      NAS_BACKING_UID: "%s"\n' "$desktop_uid"
  printf '      NAS_BACKING_GID: "%s"\n' "$host_gid"
  echo "    volumes:"
  for volume_path in "${volume_paths[@]}"; do
    volume_name="$(basename "$(dirname "$volume_path")")"
    printf '      - "%s:/mnt/fnos-raw/%s:${NAS_STORAGE_MODE:-rw}"\n' \
      "$volume_path" "$volume_name"
  done
} >"$tmp_file"
mv "$tmp_file" "$override_file"
trap - EXIT

echo "已生成 $override_file，检测到 ${#volume_paths[@]} 个存储卷："
for volume_path in "${volume_paths[@]}"; do
  printf '  %s -> /mnt/fnos/%s\n' \
    "$volume_path" "$(basename "$(dirname "$volume_path")")"
done
echo "执行 sudo docker compose up -d --force-recreate 应用配置。"
